# Generated by Django 3.2.5 on 2021-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('SI', 'Conta simples')], default='SI', max_length=2, verbose_name='tipo'),
        ),
    ]
