# Generated by Django 3.2.5 on 2021-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='pontuação'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('SI', 'Conta simples'), ('BO', 'Conta bônus')], default='SI', max_length=2, verbose_name='tipo'),
        ),
    ]
