name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: THIS_IS_NOT_SECRET
      ALLOWED_HOSTS: localhost, 127.0.0.1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntactic check
        run: |
          python manage.py check

      - name: Run Tests
        run: |
          python manage.py test
